name: expensive_management
description: "Nhung project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  shared_preferences: ^2.0.15
  google_fonts: ^6.2.1
#  flutter_app_badger: ^1.5.0
  equatable: ^2.0.5
  connectivity_plus: ^6.1.3
  flutter_secure_storage: ^9.2.4
  intl: any
  flutter_otp_text_field: ^1.1.1
  syncfusion_flutter_charts: ^28.2.5+1
  mat_month_picker_dialog: ^1.1.1

  flutter_datetime_picker_plus: ^2.1.0
  flutter_localization: ^0.3.1
  currency_picker: ^2.0.13
  flutter_switch: ^0.3.2
  permission_handler: ^11.3.1
  path_provider: ^2.0.15
  local_auth_android: ^1.0.19
  local_auth: ^2.1.5
  dio: ^5.0.1
  dio_cookie_manager: ^3.2.0
  # badges: ^3.0.2
  flutter_bloc: ^9.0.0
  open_file: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_messaging: ^15.1.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.4.2
  flutter_local_notifications: ^18.0.1

#  awesome_notifications: ^0.7.5
#  awesome_notifications_fcm: ^0.7.5

  image_picker: ^1.1.2
  cached_network_image: ^3.2.3
  share: ^2.0.4
  url_launcher: ^6.1.6
  http: ^1.3.0

  change_app_package_name: ^1.4.0


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
